### ISSUE TITLE
Deal with lists in columns?

### ISSUE THREAD

**Issue by ShanEllis** [ropenscilabs/skimr#10]
How should we handle summarizing lists in columns?

**Comment by elinw** [comment]
What kind of statistics would make sense? missing, complete, n What else?

**Comment by elinw** [comment]
I started working on this. It really has two parts because sometimes lists are "AsIs" (if they are in dataframes) but then in tibbles they can be "list" and are structured differently. AsIs was easy to do but list is not as simple because when R sees the type "list" certain functions work differently, e.g. map versus lmap.

**Comment by elinw** [comment]
I sent a PR for AsIs (which is what you get by using I() to store a list.  https://github.com/ropenscilabs/skimr/pull/92

**Comment by elinw** [comment]
Updated code merged.
