### ISSUE TITLE
Better RMarkdown functionality

### ISSUE THREAD

**Issue by kidman007** [ropenscilabs/skimr#108]
Big fan of the package. However, it is awkward to use when doing analyses in RMarkdown. 

Rather than appearing as a single concise output, like glimpse, the results manifest as multiple separate outputs, a console that is blank other than `Numeric Variables` and `Character Variables` and an html tbl_df output for every variable type in the data_frame. 

Furthermore, the tables often don't show all of the variables at once, which makes using `skim` difficult as well.

**Comment by elinw** [comment]
I think part 1 of your issue is already known and referenced in the "print doesn't work for classes other than numeric, factor or character" issues.  If you test the skim_print() refactor code this is addressed.   

Yes the output is a _list of tibbles_  one for each variable type which  is the design given that the columns are (potentially) different for each type. If you have a thought about a different way of handling that it would be great to explain, but my suggestion is to use the skim object as the basis for building a custom print method.  This aspect of the package makes it really flexible.  One could also merge the tibbles and just have NA for the statistics that don't apply for the type.

My issue with the markdown is what I think you are saying in the last paragraph. The way the tables are wrapping in the console is somewhat a matter of preference (you can modify that just like for any tibble by changing the width to Inf), but when I knit to html I really don't think that wrapping is helpful (what's the point of knitting to results you will hide) and I'd rather either have full width with a horizontal scroll or degrade the table gracefully so that the data are shown underneath.

**Comment by puterleat** [comment]
Another potential issue here is that in RStudio RMarkdown document this prints a sequence of data frames:

```
skim(mtcars)
```

The columns of which are var, type, missing, etc. But this fails because the actual return value is the tidy dataframe:

```
skim(mtcars) %>% select(var, mean, sd)
```

I had to write `names(skim(mtcars))` to work out what was going on. I'm  not sure if this is a problem with skimr or Rstudio though.

**Comment by elinw** [comment]
I think you are mixing together the skim object (which has a long, vertical structure) and the skim print object (which has a wide, horizontal structure separated out by type).  The type separation in the print object is because each type has a different set of functions (e.g. factors return different things than numeric).   If you review the readme file it explains a lot of this.
