### ISSUE TITLE
Histograms don't display correctly

### ISSUE THREAD

**Issue by jorgesinval** [ropenscilabs/skimr#142]
After outputting to docx with knitr, if I open with LibreOffice (Writer) the histograms display correctly, although if I open with Microsoft Office (word) they don't. Any idea why?

**Comment by elinw** [comment]
Hi,
 This has previously been discussed and we do need to add it to the readme.  It is because you need to use a font that supports blocks (for histograms) and braille (for line graphs).  I'm not sure what that font would be in Office.

**Comment by elinw** [comment]
Read the discussion here https://github.com/ropenscilabs/skimr/issues/136   and that may help.  I found that it took a bit of playing around with it to get it to work for me in pdf.

**Comment by jorgesinval** [comment]
Sorry, I think that I didn't understand your point. The same document (without changing the font) opens with a different look in LibreOffice's writer (appears correctly; the lowest bar doesn't seem like an indent) and in MS Word (appears the lowest bar seems like an indent and is placed above the second lowest bar). So, when you say to change the font, which font do you suggest?

**Comment by elinw** [comment]
Can you post a screenshot? 

Also:
- What is the exact font you are using?   
- When you say the "same document" do you mean you are knitting to LibreOffice, saving, and then opening the exact same document in Word or do you mean you knitting to Word and LibreOffice and getting two different results? Or something else.   
- What operating system is this on and what happens when you knit to html and pdf?  Does it work as expected in those cases?  I'm trying to see if this is a very specific Word issue.  

The fonts in LO can sometimes be slightly different since they are all open fonts, but on the other hand it could be something else.

Since I wasn't sure exactly what you had done I tried "Knit to Word" saved the file and opened it in Open Office.    Using Cambria, Arial, and Times New Roman the all displays though each one was obviously slightly different.   Screenshots below. I am on a Mac which could matter.

![word-timesnewroman](https://user-images.githubusercontent.com/754813/31321909-44a193e0-ac5b-11e7-97a4-b9994c80b471.png)
![openoffice-timesnewroman](https://user-images.githubusercontent.com/754813/31321910-477d69a4-ac5b-11e7-9e0b-5a8f88d72db5.png)

**Comment by jorgesinval** [comment]
- The font is Times New Roman.  
- When I knit to HTML it behaves normally.
- I opened the same document, without changes with different solutions.

Opening it in Office Word (Windows 10; docx): 
![image](https://user-images.githubusercontent.com/8278071/31332619-fe78474a-acde-11e7-94cf-bc6d4fbf42b5.png)

Opening it in LibreOffice Writer (Lubuntu 17.4):

![image](https://user-images.githubusercontent.com/8278071/31332703-587b0dc2-acdf-11e7-98ee-66c9a71d246b.png)

Opening it in Dropbox, the preview appears like this:
![image](https://user-images.githubusercontent.com/8278071/31332747-82e6178c-acdf-11e7-8d70-56a0a1c57e39.png)

Although, after opening it in Office Word online:

![image](https://user-images.githubusercontent.com/8278071/31332852-d668e812-acdf-11e7-91ca-db0dc6eddef7.png)

Any idea?

**Comment by elinw** [comment]
I think it could be that there are some other settings (like line height, line spacing, char spacing, display resolution etc) that are slightly different in each solution.  It could be that if you played around long enough with the deeper formatting/styling options that you could get them to be identical.  We are using `pillar` to generate the spark graphs. https://github.com/r-lib/pillar.  They recommend this font https://www.fsd.it/shop/fonts/pragmatapro/  but I don't think that will actually solve this specific issue.    

In OpenOffice I changed the style to "preformatted text"  and in Word to "SpecialString" and that helped make them a bit more consistent.

Overall we're going to have to think about how much consistency we can realistically provide to documents. Just getting the pdf to work is going to be a challenge.

**Comment by jorgesinval** [comment]
Well, I think that I achieved a possible solution, I selected the style "**Yu Gothic UI Semilight**" and look, both on MS Office Word 2016 and in the LibreOffice Writer the .docx appears gorgeous:

![image](https://user-images.githubusercontent.com/8278071/31374532-4b7c11fe-ad96-11e7-9781-fb936a4c7886.png)

I just wanted to share the solution with everyone who may have the same problem. Well, I don't know if will be the first published paper with the kind of histograms (surely it won't be), but nevertheless, I think that it will be the first to place them properly cited with your fabulous package.

I just have one more question, but is related to other functionality of the package, should I open a new issue?

**Comment by elinw** [comment]
That's great! 
Yes,  one issue per issue, it's the easiest way to keep things organized and deal with problems.

**Comment by jorgesinval** [comment]
As promised, here is the first paper in which I used the `skimr` package, really nice looking histograms:

https://www.frontiersin.org/articles/10.3389/fpsyg.2017.02229/abstract

**Comment by elinw** [comment]
Wow great!
