### ISSUE TITLE
Access output of print method to use in subsequent analyses

### ISSUE THREAD

**Issue by jrosen48** [ropenscilabs/skimr#181]
In #171, I (incorrectly) thought the output of the `print()` method / generic function was able to be used in subsequent steps, like the `skim_df` object (if I understand correctly). Would it be possible to add the option to use the output of the `print()` method - perhaps through an argument to `skim()` (i.e., `skim(return_wide = T)`) in subsequent steps? 

My goal, in particular, was to arrange the variables in this (wide) output using `dplyr::arrange()`. But I can imagine other uses, too.

**Comment by michaelquinn32** [comment]
There's been some discussion on how we can do that, and I'm sure that @elinw will be able to update you when some sort of solution is available.

In the meantime, keep in mind that the printed object isn't really what you'd expect. It takes the formatted values from the tall object and cleans then up some more. Computing on this is going to be a little hard, since everything is a character vector. It's also complicated by the fact that different variable types have different columns in the printed output.

If you want to change the order of that the summary statistics are displayed, use skim_with(). The order of the functions in the list for each type is the order that they are displayed in the table. 

For example, here are the numeric functions:
https://github.com/ropenscilabs/skimr/blob/master/R/functions.R#L129

Here's an example of changing the functions in skim_with:
https://github.com/ropenscilabs/skimr/blob/master/R/functions.R#L26

And there's many more in the the tests.
https://github.com/ropenscilabs/skimr/blob/master/tests/testthat/test-functions.R

**Comment by elinw** [comment]
I think it is worth considering a convenience function to transform the skim_df for a specific data type to a wide df and possibly a list of such data frames.  There  is come complexity with that because there are (as you see) separate data frames for each type.  That said, one benefit of piping is that after skimming you can us tidyr and dplyr to `filter()` for a given type, `select()` var, stat and value, and then `spread()` to get a wide dataframe.  One issue, however, is the problem of duplicate column names for factors and other variables which use the level variable.  Still by having the user manage that (and potentially using the other  verbs like arrange)  they actually have a lot of flexibility, more than what any function we add would give them.

The other option (which also does not address the duplicate name problem) is to make a wide dataframe without subsetting and have NA for all of the statistics that are not used. 
The downside of that is losing the class information used for formatting (e.g. knowing that a particular row should be formatted as a date variable.

**Comment by elinw** [comment]
I think an important question is whether when you say this you mean the formatted values (which are strings and can't really be processed further) or the number values (which are numeric but therefore if you try to print them will not be formatted nicely.

**Comment by elinw** [comment]
I have been looking at this today and I'm wondering if rather than reinvent the tidyverse wheel, which is already available in all its glory and with helpers via piping (or inside the skim.df() data set definiton), we should just focus on the very specific case of one variable.   Anything more than that we can say you have to process your own subsetting using the methods of your choice, whether tidyverse, base R or something else.

If we did that, we'd then be back to the various other thoughts. That is

- create skim.vector
- create a print method for skim_v
- coerce anything that is not a data frame into a data frame.
- other

It seems to me that if we created skim.vector() we could achieve the goal of making skim_v internal and use skim.vector as a way to access the internal function. Print.skim_v on the other hand prevents us from making that function internal.  

That said, the question then is whether the output of skim.vector() should be a vector or a data frame. It feels weird to me to put in a vector and get out a skim_df data frame but a data frame would mean we could keep piping and subsequently use tidyverse verbs plus it would easily be able to use print.skim_df.  On the other hand returning a vector we would be type consistent but would have to make print.skim_vector.  

Thoughts?

**Comment by elinw** [comment]
I was playing around with the concept of utility functions for making wide data frames for value and formatted values separately (e.g `skim_wide_value()` and `skim_wide_formatted()`.  If we put all of the data in one data frame then the statistics that are not calculated for a class would be NA. There is some thinking to be done about the levels issue because it produces duplicate column names, but maybe something like `top_counts.Virginica` etc would work.

**Comment by elinw** [comment]
@jrosen48 You can see this work in the convenience branch. It has a few "notes" so I won't make a PR until I deal with them. Let me know if that's what you are looking for.

**Comment by elinw** [comment]
THis is the new take on getting the wide data.  https://github.com/ropenscilabs/skimr/pull/196/ It puts it into a single data frame so NAs where a type does not have a  given statistics.

**Comment by elinw** [comment]
Added a function to make a list of tibbles, one for each type.  It is not a normal tidyverse thing but it is something people will find useful (as we can see from the requests in  the issue tracker). 
@jrosen48 @michaelquinn32

**Comment by elinw** [comment]
Merged #202 Which adds functions to return a wide single data frame with NAs (skim_to_wide()) and a list of the separate data frames for each type (skim_to_list).
