### ISSUE TITLE
Min() and Max() produce unexpected values when used on all NA vectors

### ISSUE THREAD

**Issue by elinw** [ropenscilabs/skimr#224]
https://github.com/ropenscilabs/skimr/issues/221

If we have a numeric column that is all NA then min() and max() of Inf and -Inf are produced and also we get warnings.
One suggestion is to change the default statistics to quantile() with probs=c(0) and probs = c(1).

**Comment by rgayler** [comment]
Copying the relevant points from #221 

> Three arguments in favour of using [the definition from] quantile:
> 
> 1. Conceptually - I think returning NA for min and max is what most people
> would expect. Inf and -Inf are specific values that are not present in the
> input vector. min and max are reducing functions that use Inf and -Inf as
> their starting values to deal with the degenerate case of 0 input arguments
> (for the same reason that sum() = 0 and prod() = 1).
> 
> 2. It would return the same values as summary(), which many people would
> turn to when they want to cross-check what skim is telling them.
> 
> 3. When people are using a skim_df I think they are much more likely to
> test for is.na() than is.infinite(). I can see a lot of [people]
> spending an hour before they work that out.

**Comment by elinw** [comment]
One question @michaelquinn32 and I discussed was whether returning something called max that is different than max() is a good idea (same for min).  Of course summary already does this, but this does make me also think about documenting what each of those functions is in skim.

**Comment by rgayler** [comment]
> does make me also think about documenting what each of those functions is
in skim

I agree. If anyone is using skimr seriously, at some point they will want
to know precisely what it is doing on the inside without having to dive
into the code. (Everything has arguable variations if you look hard enough,
e.g. the choice of 9 algorithms in quantile.)

**Comment by elinw** [comment]
The question for me is where to document.

**Comment by rgayler** [comment]
FWIW I have **never** been able to find the skimr vignettes - so, for me, it would have to be in the function documentation.

**Comment by elinw** [comment]
Great you are getting the prize for bug finding, I think we neglected to put in the code to link to them from the package page.

**Comment by rgayler** [comment]
Yay me?

**Comment by elinw** [comment]
Did you install from CRAN or github?  I think that you need to force the vignettes to build with install_github() ... I can see that I don't have them locally but I just installed from CRAN on a different box and they are there.  I think @jimhester  and I have discussed it before.

**Comment by rgayler** [comment]
That's it.

Currently installed from Github (1.0.1) - vignettes not visible
Uninstall and reinstall from CRAN (1.0) - Vignettes visible - yay!
Uninstall and reinstall from Github (1.0.1) - vignettes not visible

**Comment by michaelquinn32** [comment]
Hi Ross!

Thanks for pointing this out.

Per confusing max/ min values, R defines the max of an empty set to be -Inf. This surprising result comes from real analysis:

https://math.stackexchange.com/questions/432295/infimum-and-supremum-of-the-empty-set

Confusingly, summary() uses the quantile function instead of the Primitive max and min functions in R, masking this default behavior. Good R style promotes using primitives when reasonable (despite the fact that they can behave differently), and we currently follow that route:

http://adv-r.had.co.nz/Functions.html#function-components

Do you believe that it is better to follow summary closer? This is a design goal that we have eschewed before, because summary does a bunch of unexpected things, but we could tack back a bit.

Thanks for all of the help!

**Comment by rgayler** [comment]
Hi Michael & Elin,

Thanks for the useful package. I think my two strongest arguments for NA rather than +/-Inf are:

1. From  a usability point of view I think the conceptual models that users bring to the task are more important than the conceptual models that the developers have. I suspect (but who can tell without some empirical work) that when a data analyst user sees the label "min" they think "This will contain the smallest value actually found in my data, if all the values happen to be equal then it will return that value (which will also be the max value)" rather than "This will contain the result of applying the mathematical min function to the set of values occurring in my data having first taken the preprocessing step of treating each row value as a singleton set, mapping any NA values to empty sets, then calculating the union of all the row sets". (<== You can see that I don't think the handling of NA values is actually part of the mathematical definition of min and max - rather they are non-comparable value that need to be filtered out first.)

2. The argument i made 5-ish days ago that when a user is programming with the skim_df object it is more awkward to have to test for Inf in some statistics and NA in the other statistics (besides which many more users will be familiar with NA than Inf). I think this is the strongest argument.

Cheers

Ross

**Comment by elinw** [comment]
@rgayler @michaelquinn32  Edge cases are always hard.  One question I have is whether if we switched to using `quantile(x, probs=c(0))`  it would be better to label that as p0. Here's why.  If the user ran the statstics on their own and they tried `min() ` they will get one thing and if they use quantile they get another.  Of course it doesn't help that we are using compact names like `p75` that don't actually match the function name.

**Comment by rgayler** [comment]
Yes - I think p0 is a better label if you are using `quantile(x, probs=c(0))` because it is both more consistent with the underlying mechanism and more systematically related to the other quantile labels (e.g. p75). In fact this is what I always did in the past (pre `skimr`) when I would use `dplyr::mutate` and `quantile` to construct distribution summaries.

**Comment by elinw** [comment]
Okay here's what it looks like https://github.com/ropenscilabs/skimr/pull/237

I have no idea what is going on with the one failing test which has no restart button, it looks like a Travis issue (currently Travis is dealing with a problem).
